### PR TITLE
Maintenance: Remove trailing whitespaces, upgrade to Python 3 syntax, add pre-commit configuration

### PR DESCRIPTION
**Pull request by EwoutH**
This PR does two maintenance things:
 - It removes all trailing whitespaces
 - It upgrades leftover Python 2 code to the Python 3 syntax

It also adds a pre-commit configuration, defined in `.pre-commit-config.yaml`,  which checks for these things automatically. It checks once a month if there are any updates, so it's easy on maintanance.

pre-commit can be enabled on https://pre-commit.ci/.

There are a lot of other pre-commit hooks available that check automatically for things, see https://pre-commit.com/hooks.html.

### CODE REVIEW

**Comment by EwoutH** [comment]
@dhadka What do you think of this?

**Comment by dhadka** [comment]
It looks good to me.  I'll follow up after merging to see if we can remove `six`.

**Review by dhadka — APPROVED** [review]

**Comment by EwoutH** [comment]
> pre-commit can be enabled on https://pre-commit.ci/.

I would highly recommend enabling pre-commit.ci, since that will help keep the pre-commit configuration up to date and make sure every PR conforms to the requirements.

**Comment by dhadka** [comment]
I'll take a look, haven't used that before.  I'm also looking at adding `flake8` during CI - https://github.com/Project-Platypus/Platypus/pull/229

**Pull request merged**
